// Unit tests for predefined file loading (Phase 6 US-004).
//
// AC-16: workspace .em.predefined declaring host_t makes host_t.foo() resolvable.
// §A7:   ENMA_LSP_TEST=1 skips bundled predefined.
//
// These tests exercise loadBundledPredefined(), loadPredefinedFile(), and the
// Inspector integration, NOT the full LSP pipeline.

import * as assert from 'node:assert/strict';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';

// ---- helpers ---------------------------------------------------------------

/** Resolve the bundled predefined file path relative to the repo root. */
function findBundledPredefined(): string | undefined {
    const candidates = [
        path.resolve(__dirname, '..', '..', '..', 'src', 'predefined', 'enma-stdlib.em.predefined'),
        path.resolve(__dirname, '..', '..', '..', '..', 'src', 'predefined', 'enma-stdlib.em.predefined'),
    ];
    for (const c of candidates) {
        if (fs.existsSync(c)) return c;
    }
    return undefined;
}

// ---- Test 1: bundled predefined loads when ENMA_LSP_TEST is unset ----------

describe('Predefined loading — bundled', () => {
    it('bundled file exists on disk (regenerated by Task A)', () => {
        const p = findBundledPredefined();
        assert.ok(p !== undefined, 'enma-stdlib.em.predefined should exist; run npm run regenerate-stdlib');
        assert.ok(fs.existsSync(p!), `file not found at ${p}`);
    });

    it('loadPredefinedFile() reads and hoists bundled file without errors', () => {
        // We need to load without ENMA_LSP_TEST=1 being set for this test.
        // Temporarily unset it for this test scope.
        const prevEnv = process.env.ENMA_LSP_TEST;
        delete process.env.ENMA_LSP_TEST;
        try {
            // Dynamically import to avoid module-level ENMA_LSP_TEST guards
            // (module cache means this was loaded before; test runs after _helpers set it).
            // Instead, call the loader function directly.
            const { loadPredefinedFile } = require('../../../src/inspector/predefinedLoader');
            const p = findBundledPredefined();
            if (!p) {
                assert.fail('bundled predefined file not found');
            }
            const rec = loadPredefinedFile(p, 'bundled');
            assert.ok(rec !== undefined, 'loadPredefinedFile should return a record');
            assert.equal(rec.origin, 'bundled');
            assert.equal(rec.diagnostics.length, 0, `expected 0 parse diagnostics, got: ${rec.diagnostics.map((d: {message: string}) => d.message).join(', ')}`);
            // coroutine_t, variant, array should be present
            const scope = rec.globalScope;
            assert.ok(scope.lookupSymbol('coroutine_t') !== undefined, 'coroutine_t should be declared');
            assert.ok(scope.lookupSymbol('variant') !== undefined, 'variant should be declared');
            assert.ok(scope.lookupSymbol('array') !== undefined, 'array should be declared');
        } finally {
            if (prevEnv !== undefined) process.env.ENMA_LSP_TEST = prevEnv;
            else delete process.env.ENMA_LSP_TEST;
        }
    });

    it('ENMA_LSP_TEST=1: loadBundledPredefined() returns []', () => {
        const prev = process.env.ENMA_LSP_TEST;
        process.env.ENMA_LSP_TEST = '1';
        try {
            const { loadBundledPredefined } = require('../../../src/inspector/predefinedLoader');
            const recs = loadBundledPredefined();
            assert.ok(Array.isArray(recs), 'should return an array');
            assert.equal(recs.length, 0, 'should return [] when ENMA_LSP_TEST=1');
        } finally {
            if (prev !== undefined) process.env.ENMA_LSP_TEST = prev;
            else delete process.env.ENMA_LSP_TEST;
        }
    });

    it('bundled predefined includes global function println', () => {
        const prevEnv = process.env.ENMA_LSP_TEST;
        delete process.env.ENMA_LSP_TEST;
        try {
            const { loadPredefinedFile } = require('../../../src/inspector/predefinedLoader');
            const p = findBundledPredefined();
            if (!p) return; // skip if regeneration hasn't run
            const rec = loadPredefinedFile(p, 'bundled');
            if (!rec) return;
            const sym = rec.globalScope.lookupSymbol('println');
            assert.ok(sym !== undefined, 'println global function should be present');
        } finally {
            if (prevEnv !== undefined) process.env.ENMA_LSP_TEST = prevEnv;
            else delete process.env.ENMA_LSP_TEST;
        }
    });
});

// ---- Test 2: workspace predefined files ------------------------------------

describe('Predefined loading — workspace files', () => {
    let tmpDir: string;

    beforeEach(() => {
        tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'enma-pred-test-'));
    });

    afterEach(() => {
        fs.rmSync(tmpDir, { recursive: true, force: true });
    });

    it('workspace .em.predefined declaring host_t makes host_t resolvable', () => {
        process.env.ENMA_LSP_TEST = '1';
        const src = `class host_t {\n    int64 foo();\n    void bar(string p0);\n}\n`;
        const predFile = path.join(tmpDir, 'host.em.predefined');
        fs.writeFileSync(predFile, src, 'utf8');

        const { loadPredefinedFile } = require('../../../src/inspector/predefinedLoader');
        const rec = loadPredefinedFile(predFile, 'workspace');
        assert.ok(rec !== undefined, 'should load workspace predefined');
        assert.equal(rec.diagnostics.length, 0, 'workspace predefined should parse cleanly');
        const sym = rec.globalScope.lookupSymbol('host_t');
        assert.ok(sym !== undefined, 'host_t should be declared in scope');
    });

    it('multiple workspace .em.predefined files all loaded via scanWorkspacePredefined', () => {
        process.env.ENMA_LSP_TEST = '1';
        const src1 = `class TypeA {\n    int64 methodA();\n}\n`;
        const src2 = `class TypeB {\n    string methodB();\n}\n`;
        fs.writeFileSync(path.join(tmpDir, 'a.em.predefined'), src1, 'utf8');
        fs.writeFileSync(path.join(tmpDir, 'b.em.predefined'), src2, 'utf8');

        const { scanWorkspacePredefined } = require('../../../src/inspector/predefinedLoader');
        const recs = scanWorkspacePredefined(tmpDir);
        assert.equal(recs.length, 2, `expected 2 records, got ${recs.length}`);
        const names = recs.map((r: { globalScope: { lookupSymbol: (n: string) => unknown } }) =>
            r.globalScope.lookupSymbol('TypeA') !== undefined ? 'TypeA' :
            r.globalScope.lookupSymbol('TypeB') !== undefined ? 'TypeB' : '?'
        );
        assert.ok(names.includes('TypeA'), 'TypeA should be loaded');
        assert.ok(names.includes('TypeB'), 'TypeB should be loaded');
    });
});
