// Test: working full grammar + complex number rule
module.exports = grammar({
  name: 'enma',
  extras: ($) => [/\s/, $.comment],
  word: ($) => $.identifier,
  rules: {
    translation_unit: ($) => repeat($._item),
    _item: ($) => choice($.preprocessor, $.block, $.expression_statement),
    preprocessor: ($) => seq('#', field('directive', $.identifier), optional(field('arg', $._rest_of_line))),
    _rest_of_line: ($) => /[^\n]+/,
    expression_statement: ($) => seq($._expr, ';'),
    block: ($) => seq('{', repeat($._item), '}'),
    _expr: ($) => repeat1($._expr_part),
    _expr_part: ($) => choice(
      $.identifier, $.number, $.string, $.f_string, $.char_literal,
      $.parenthesized, $.bracketed,
      '=', '+=', '-=', '*=', '/=', '%=', '&=', '|=', '^=',
      '||', '&&', '==', '!=', '<', '>', '<=', '>=',
      '|', '^', '&', '+', '-', '*', '/', '%',
      '.', '->', '::', '++', '--', '!', '~',
      '?', ':', ',', '...', '@',
      'new', 'delete', 'sizeof', 'typeof',
      'cast', 'static_cast', 'reinterpret_cast', 'const_cast',
      'true', 'false', 'null', 'nullptr', 'this',
      'if', 'else', 'for', 'while', 'do', 'switch', 'match',
      'case', 'default', 'break', 'continue', 'return',
      'try', 'catch', 'throw', 'defer', 'yield', 'goto',
      'class', 'struct', 'interface', 'enum', 'namespace',
      'using', 'template', 'typedef', 'mixin', 'import',
      'extern', 'delegate', 'property', 'coroutine', 'typename',
      'operator', 'function',
      'static', 'const', 'constexpr', 'override',
      'public', 'private', 'protected', 'virtual',
      'abstract', 'final', 'shared', 'inline',
      'nullable', 'out', 'auto', 'volatile', 'get', 'set',
      'int8', 'int16', 'int32', 'int64',
      'uint8', 'uint16', 'uint32', 'uint64',
      'aint8', 'aint16', 'aint32', 'aint64',
      'float32', 'float64', 'float', 'double',
      'string', 'wstring', 'char', 'wchar',
      'bool', 'void', 'size_t',
      'array', 'map', 'hash_set', 'sorted_map', 'variant',
      'vec2', 'vec3', 'vec4',
      'coroutine_t', 'atomic_int32', 'atomic_int64',
      'mutex', 'cond_var', 'lock_guard',
      'file_t', 'regex', 'json_value',
    ),
    parenthesized: ($) => seq('(', repeat($._expr_part), ')'),
    bracketed: ($) => seq('[', repeat($._expr_part), ']'),
    number: ($) => choice(
      token(/0[xX][0-9a-fA-F_]+/),
      token(/(\d+\.\d*|\.\d+)([eE][+-]?\d+)?/),
      token(/\d[\d']*/),
    ),
    string: ($) => seq('"', repeat(choice(token.immediate(/[^"\\]+/), $.escape)), '"'),
    f_string: ($) => seq('f', '"', repeat(choice(token.immediate(/[^"\\{]+/), $.escape, $.interpolation)), '"'),
    interpolation: ($) => seq('{', repeat($._expr_part), '}'),
    char_literal: ($) => seq("'", choice($.escape, /[^'\\]/), "'"),
    escape: ($) => token.immediate(/\\(x[0-9A-Fa-f]{1,4}|u[0-9A-Fa-f]{1,8}|.)/),
    identifier: ($) => /[A-Za-z_][A-Za-z0-9_]*/,
    comment: ($) => choice(seq('//', /.*/), seq('/*', /[^*]*\*+([^/*][^*]*\*+)*/, '/')),
  },
});
